Fix fatal error on node require.
Before:

$ node
> var isOperaMini = require('is-opera-mini');
ReferenceError: window is not defined
    at Object.<anonymous> ([...]/node_modules/is-opera-mini/index.js:2:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at repl:1:19
    at REPLServer.defaultEval (repl.js:248:27)
    at bound (domain.js:287:14)

After:

$ node
> var isOperaMini = require('is-opera-mini');
undefined
> console.log(isOperaMini);
false

See also:
http://stackoverflow.com/a/4224668/349353